extends Node

func _ready():
	preload("res://scripts/Food/MenuItems/bolognese.gd")
	preload("res://scripts/Food/MenuItems/bread.gd")
	preload("res://scripts/Food/MenuItems/brownies.gd")
	preload("res://scripts/Food/MenuItems/burger_beef.gd")
	preload("res://scripts/Food/MenuItems/burger_chicken.gd")
	preload("res://scripts/Food/MenuItems/burger_fish.gd")
	preload("res://scripts/Food/MenuItems/cheese_bread.gd")
	preload("res://scripts/Food/MenuItems/fish_and_chips.gd")
	preload("res://scripts/Food/MenuItems/garlic_bread.gd")
	preload("res://scripts/Food/MenuItems/icecream_chocolate.gd")
	preload("res://scripts/Food/MenuItems/icecream_strawberry.gd")
	preload("res://scripts/Food/MenuItems/icecream_vani.gd")
	preload("res://scripts/Food/MenuItems/mac_and_cheese.gd")
	preload("res://scripts/Food/MenuItems/onion_rings.gd")
	preload("res://scripts/Food/MenuItems/pie_apple.gd")
	preload("res://scripts/Food/MenuItems/pie_pineapple.gd")
	preload("res://scripts/Food/MenuItems/pie_pumpkin.gd")
	preload("res://scripts/Food/MenuItems/pizza_cheese.gd")
	preload("res://scripts/Food/MenuItems/pizza_hawaiian.gd")
	preload("res://scripts/Food/MenuItems/pizza_meat.gd")
	preload("res://scripts/Food/MenuItems/soup_mushroom.gd")
	preload("res://scripts/Food/MenuItems/soup_onion.gd")
	preload("res://scripts/Food/MenuItems/soup_pumpkin.gd")
	preload("res://scripts/Food/MenuItems/soup_tomato.gd")
	preload("res://scripts/Food/MenuItems/steak_and_chips.gd")
	preload("res://scripts/Food/MenuItems/taco_beef.gd")
	preload("res://scripts/Food/MenuItems/taco_chicken.gd")
	preload("res://scripts/Food/MenuItems/taco_mushroom.gd")
